sudo: false
language: node_js
node_js:
- 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
  - master # build master branch only
script:
- hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: 5e9267b6ea6a05b7f42d9279881ef9680c307564
  keep-history: true
  on:
    branch: master
  local-dir: public